## Pandas `DataFrames` 
* Vettore a due dimensioni migliorato.
* Può avere indici personalizzati di riga e colonna.
* Offre capacità e operazioni ideali per programmazione orientata alla data-science.
* Supporta dati mancanti
* Ogni colonna di un `DataFrame` è detta `Series`

### Creare un `DataFrame` da un dizionario
* Il dizionario deve avere delle liste come valori.

In [1]:
import pandas as pd

In [2]:
grades_dict = {'Wally': [87, 96, 70], 'Eva': [100, 87, 90],
               'Sam': [94, 77, 90], 'Katie': [100, 81, 82],
               'Bob': [83, 65, 85]}

In [3]:
grades = pd.DataFrame(grades_dict)

* Pandas mostra i `DataFrame` in formato tabellare con _allineamento a sinistra_ nella colonna degli indici (righe) e _a destra_ per le restanti colonne.

In [5]:
grades

   Wally  Eva  Sam  Katie  Bob
0     87  100   94    100   83
1     96   87   77     81   65
2     70   90   90     82   85

### Personalizzare gli indici dei `DataFrame` 
* Si può usare l'**attributo `index`** per cambiare gli indici del `DataFrame` da interi consecutivi a **etichette**
* Bisogna fornire una collezione a una dimensione che ha lo stesso numero di elementi delle  _righe_ del `DataFrame`

In [15]:
grades.index = ['Test1', 'Test2', 'Test3']

In [16]:
grades

       Wally  Eva  Sam  Katie  Bob
Test1     87  100   94    100   83
Test2     96   87   77     81   65
Test3     70   90   90     82   85

### Accedere alle colonne del `DataFrame` 
* Si può accedere ai dati del `DataFrame` in diverse maniere a seconda di quella più conveniente.
* Per esempio: accedere ai voti di `Eva` per nome e mostrare la colonna come una `Series`

In [18]:
grades['Eva']

Test1    100
Test2     87
Test3     90
Name: Eva, dtype: int64

### Filtri booleani (boolean indexing)
* La selezione più potente in un `DataFrame` è detta **filtro booleano (Boolean indexing)**
* Esempio, selezionare le i voti maggiori o uguali al 90:
    * Pandas controlla ogni voto e determina se è maggiore o uguale al 90 e, se sì, lo include nel nuovo `DataFrame`.
    * I voti per cui la condizione è `False` sono rappresentati da **`NaN` (not a number)** nel nuovo `DataFrame`.

In [19]:
grades[grades >= 90]

       Wally    Eva   Sam  Katie  Bob
Test1    NaN  100.0  94.0  100.0  NaN
Test2   96.0    NaN   NaN    NaN  NaN
Test3    NaN   90.0  90.0    NaN  NaN

* Selezionare tutti i voti compresi fra 80 e 89

In [20]:
grades[(grades >= 80) & (grades < 90)]

       Wally   Eva  Sam  Katie   Bob
Test1   87.0   NaN  NaN    NaN  83.0
Test2    NaN  87.0  NaN   81.0   NaN
Test3    NaN   NaN  NaN   82.0  85.0

* Le **maschere** booleane di Pandas usano gli operatori _bitwise_ per combinare varie condizion.
* Si usa `&` (bitwise AND), _non_ l'operatore `and` e, al posto di `or`, si usa `|` (bitwise OR)
* NumPy ha un meccanismo simile di filtro booleano per gli `array`
* ATTENZIONE: Se la selezione riguarda non i singoli valori, ma intere righe/colonne, il nuovo `DataFrame` ne avrà un numero minore (le righe/colonne di soli NaN sono eliminate).

# APPROFONDIMENTI: ALTRI MODI PER SELEZIONARE RIGHE/COLONNE NEI DataFrame

### Selecting Rows via the `loc` and `iloc` Attributes
* `DataFrame`s support indexing capabilities with `[]`, but pandas documentation recommends using the attributes `loc`, `iloc`, `at` and `iat`
    * Optimized to access `DataFrame`s and also provide additional capabilities 
* Access a row by its label via the `DataFrame`’s **`loc` attribute**

In [21]:
grades.loc['Test1']

Wally     87
Eva      100
Sam       94
Katie    100
Bob       83
Name: Test1, dtype: int64

* Access rows by integer zero-based indices using the **`iloc` attribute** (the `i` in `iloc` means that it’s used with integer indices)

In [24]:
grades.iloc[0]

Wally     87
Eva      100
Sam       94
Katie    100
Bob       83
Name: Test1, dtype: int64

### Selecting Rows via Slices and Lists with the `loc` and `iloc` Attributes
* Index can be a _slice_
* When using slices containing **labels** with `loc`, the range specified **includes** the high index (`'Test3'`):

In [25]:
grades.loc['Test1':'Test3']

       Wally  Eva  Sam  Katie  Bob
Test1     87  100   94    100   83
Test2     96   87   77     81   65
Test3     70   90   90     82   85

* When using slices containing **integer indices** with `iloc`, the range you specify **excludes** the high index (`2`):

In [99]:
grades.iloc[0:2]

       Wally  Eva  Sam  Katie  Bob
Test1     87  100   94    100   83
Test2     96   87   77     81   65

* Select _specific rows_ with a _list_

In [100]:
grades.loc[['Test1', 'Test3']]

       Wally  Eva  Sam  Katie  Bob
Test1     87  100   94    100   83
Test3     70   90   90     82   85

In [101]:
grades.iloc[[0, 2]]

       Wally  Eva  Sam  Katie  Bob
Test1     87  100   94    100   83
Test3     70   90   90     82   85

### Selecting Subsets of the Rows and Columns 
* View only `Eva`’s and `Katie`’s grades on `Test1` and `Test2`

In [102]:
grades.loc['Test1':'Test2', ['Eva', 'Katie']]

       Eva  Katie
Test1  100    100
Test2   87     81

* Use `iloc` with a list and a slice to select the first and third tests and the first three columns for those tests

In [103]:
grades.iloc[[0, 2], 0:3]

       Wally  Eva  Sam
Test1     87  100   94
Test3     70   90   90

### Accessing a Specific `DataFrame` Cell by Row and Column
* `DataFrame` method **`at`** and **`iat`** attributes get a single value from a `DataFrame`

In [104]:
grades.at['Test2', 'Eva']

np.int64(87)

In [105]:
grades.iat[2, 0]

np.int64(70)

* Can assign new values to specific elements

In [115]:
grades.at['Test2', 'Eva'] = 100

In [116]:
grades.at['Test2', 'Eva']

np.int64(100)

In [117]:
grades.iat[1, 2] = 87

In [118]:
grades.iat[1, 2]

np.int64(87)

In [120]:
grades.at['Test2', 'Sam']

np.int64(87)

### Descriptive Statistics
* `DataFrame`s **`describe` method** calculates basic descriptive statistics for the data and returns them as a `DataFrame`
* Statistics are calculated by column

In [27]:
grades.describe()

           Wally         Eva        Sam       Katie        Bob
count   3.000000    3.000000   3.000000    3.000000   3.000000
mean   84.333333   92.333333  87.000000   87.666667  77.666667
std    13.203535    6.806859   8.888194   10.692677  11.015141
min    70.000000   87.000000  77.000000   81.000000  65.000000
25%    78.500000   88.500000  83.500000   81.500000  74.000000
50%    87.000000   90.000000  90.000000   82.000000  83.000000
75%    91.500000   95.000000  92.000000   91.000000  84.000000
max    96.000000  100.000000  94.000000  100.000000  85.000000

* Quick way to summarize your data
* Nicely demonstrates the power of array-oriented programming with a clean, concise functional-style call
* Can control the precision and other default settings with pandas’ **`set_option` function**

In [28]:
pd.set_option('precision', 2)

OptionError: Pattern matched multiple keys

In [29]:
grades.describe()

           Wally         Eva        Sam       Katie        Bob
count   3.000000    3.000000   3.000000    3.000000   3.000000
mean   84.333333   92.333333  87.000000   87.666667  77.666667
std    13.203535    6.806859   8.888194   10.692677  11.015141
min    70.000000   87.000000  77.000000   81.000000  65.000000
25%    78.500000   88.500000  83.500000   81.500000  74.000000
50%    87.000000   90.000000  90.000000   82.000000  83.000000
75%    91.500000   95.000000  92.000000   91.000000  84.000000
max    96.000000  100.000000  94.000000  100.000000  85.000000

* For student grades, the most important of these statistics is probably the mean
* Can calculate that for each student simply by calling `mean` on the `DataFrame`

In [30]:
grades.mean()

Wally    84.333333
Eva      92.333333
Sam      87.000000
Katie    87.666667
Bob      77.666667
dtype: float64

### Transposing the `DataFrame` with the `T` Attribute
* Can quickly **transpose** rows and columns—so the rows become the columns, and the columns become the rows—by using the **`T` attribute** to get a view

In [31]:
grades.T

       Test1  Test2  Test3
Wally     87     96     70
Eva      100     87     90
Sam       94     77     90
Katie    100     81     82
Bob       83     65     85

* Assume that rather than getting the summary statistics by student, you want to get them by test
* Call `describe` on `grades.T`

In [32]:
grades.T.describe()

            Test1     Test2      Test3
count    5.000000   5.00000   5.000000
mean    92.800000  81.20000  83.400000
std      7.661593  11.54123   8.234076
min     83.000000  65.00000  70.000000
25%     87.000000  77.00000  82.000000
50%     94.000000  81.00000  85.000000
75%    100.000000  87.00000  90.000000
max    100.000000  96.00000  90.000000

* Get average of all the students’ grades on each test

In [68]:
grades.T.mean()

Test1    92.8
Test2    85.8
Test3    83.4
dtype: float64

### Sorting by Rows by Their Indices
* Can sort a `DataFrame` by its rows or columns, based on their indices or values
* Sort the rows by their _indices_ in _descending_ order using **`sort_index`** and its keyword argument `ascending=False`

In [38]:
grades.sort_index(ascending=False)

       Wally  Eva  Sam  Katie  Bob
Test3     70   90   90     82   85
Test2     96   87   77     81   65
Test1     87  100   94    100   83

### Sorting by Column Indices
* Sort columns into ascending order (left-to-right) by their column names
* **`axis=1` keyword argument** indicates that we wish to sort the _column_ indices, rather than the row indices
    * `axis=0` (the default) sorts the _row_ indices

In [43]:
grades.sort_index(axis=1)

       Bob  Eva  Katie  Sam  Wally
Test1   83  100    100   94     87
Test2   65   87     81   77     96
Test3   85   90     82   90     70

### Sorting by Column Values
* To view `Test1`’s grades in descending order so we can see the students’ names in highest-to-lowest grade order, call method **`sort_values`**
* `by` and `axis` arguments work together to determine which values will be sorted
    * In this case, we sort based on the column values (`axis=1`) for `Test1`

In [49]:
grades.sort_values(by='Test1', axis=1, ascending=False)

       Eva  Katie  Sam  Wally  Bob
Test1  100    100   94     87   83
Test2   87     81   77     96   65
Test3   90     82   90     70   85

* Might be easier to read the grades and names if they were in a column
* Sort the transposed `DataFrame` instead

In [52]:
grades.T.sort_values(by='Test1', ascending=False)

       Test1  Test2  Test3
Eva      100     87     90
Katie    100     81     82
Sam       94     77     90
Wally     87     96     70
Bob       83     65     85

* Since we’re sorting only `Test1`’s grades, we might not want to see the other tests at all
* Combine selection with sorting

In [53]:
grades.loc['Test1'].sort_values(ascending=False)

Eva      100
Katie    100
Sam       94
Wally     87
Bob       83
Name: Test1, dtype: int64

### Copy vs. In-Place Sorting
* `sort_index` and `sort_values` return a _copy_ of the original `DataFrame`
* Could require substantial memory in a big data application
* Can sort _in place_ by passing the keyword argument `inplace=True`

------
&copy;1992&ndash;2020 by Pearson Education, Inc. All Rights Reserved. This content is based on Chapter 5 of the book [**Intro to Python for Computer Science and Data Science: Learning to Program with AI, Big Data and the Cloud**](https://amzn.to/2VvdnxE).

DISCLAIMER: The authors and publisher of this book have used their 
best efforts in preparing the book. These efforts include the 
development, research, and testing of the theories and programs 
to determine their effectiveness. The authors and publisher make 
no warranty of any kind, expressed or implied, with regard to these 
programs or to the documentation contained in these books. The authors 
and publisher shall not be liable in any event for incidental or 
consequential damages in connection with, or arising out of, the 
furnishing, performance, or use of these programs.